# Generated by Django 4.0.3 on 2022-03-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
