# Generated by Django 4.0.3 on 2022-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_dish_author'),
        ('users', '0008_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_dish',
            field=models.ManyToManyField(to='recipes.dish'),
        ),
    ]
