# Generated by Django 4.0.3 on 2022-03-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.TextField()),
                ('ingredients_input', models.TextField()),
                ('ingredients_num', models.CharField(max_length=3)),
                ('time_cook', models.CharField(max_length=20)),
                ('recipe', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.dishcategory')),
            ],
        ),
    ]
