# Generated by Django 4.0.3 on 2022-03-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ингредиент')),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.dishcategory', verbose_name='категория блюда'),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients_input',
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients_num',
            field=models.CharField(max_length=3, verbose_name='количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='introduction',
            field=models.TextField(verbose_name='краткое описание блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, verbose_name='наименование блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.TextField(verbose_name='рецепт блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='time_cook',
            field=models.CharField(max_length=20, verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='dish_category',
            field=models.CharField(max_length=150, verbose_name='категория блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_input',
            field=models.ManyToManyField(to='recipes.ingredients', verbose_name='ингредиенты'),
        ),
    ]
