# Generated by Django 4.0.3 on 2022-03-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredients_alter_dish_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='time_cook',
            field=models.TimeField(max_length=20, verbose_name='время приготовления'),
        ),
    ]
