# Generated by Django 4.0.3 on 2022-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/recipes', verbose_name='Картики категорий'),
        ),
    ]
