# Generated by Django 4.0.3 on 2022-03-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_dish_time_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='time_cook',
            field=models.TextField(max_length=20, verbose_name='время приготовления'),
        ),
    ]
