# Generated by Django 4.0.3 on 2022-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_dishcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='intro',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
