# Generated by Django 4.0.3 on 2022-03-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_dish_time_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='time_cook',
            field=models.CharField(max_length=30, verbose_name='время приготовления'),
        ),
    ]
