# Generated by Django 4.0.3 on 2022-03-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_dish_time_cook'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients_input',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_input',
            field=models.TextField(default=1, verbose_name='ингредиенты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients_num',
            field=models.CharField(max_length=3),
        ),
    ]
